train:
  _target_: src.datasets.GridRoadDataset
  cell_size: ${model.patch_size}
  image_size: 1024 
  data_path: "road_data/external/train/images"
  target_path: "road_data/train/groundtruth"

inference:
  _target_: src.datasets.GridRoadDataset
  cell_size: ${model.patch_size}
  image_size: 400
  data_path: "road_data/validation/images"
  target_path: "road_data/validation/groundtruth"