train:
  _target_: src.datasets.ImageRoadDataset
  data_path: "road_data/train/images"
  target_path: "road_data/train/groundtruth"

inference:
  _target_: src.datasets.ImageRoadDataset
  data_path: "road_data/validation/images"
  target_path: "road_data/validation/groundtruth"