train: 
  - _target_: src.metrics.AccuracyMetric
    name: "accuracy"
  - _target_: src.metrics.F1Metric
    name: "f1"

inference:
  - _target_: src.metrics.AccuracyMetric
    name: "accuracy"
  - _target_: src.metrics.F1Metric
    name: "f1"
