train:
  _target_: src.transforms.CustomTransform
  patch_size: ${model.patch_size}
  road_threshold: 0.25

inference:
  _target_: src.transforms.BaselineTransform
  road_threshold: 0.25

test:
  _target_: src.transforms.BaselineTransform
  road_threshold: 0.25
