_target_: src.model.UNet

# patch_size: 304

in_channels: 3 
num_classes: 1

#DeSIGN:
use_direct_stride: False  # Boolean parameter to control stride behavior
nrChannels1: 4           # Number of channels for the first set of layers
nrChannels2: 8          # Number of channels for the second set of layers
nrChannels3: 12           # Number of channels for the third set of layers
nrChannels4: 16          # Number of channels for the fourth set of layers
drop_prob: 0.01       # Dropout probability

## So far best configuration got 82.5% on the validation set