_target_: src.model.UNet

# patch_size: 304

in_channels: 3 
num_classes: 1

#DeSIGN:
use_direct_stride: False  # Boolean parameter to control stride behavior
nrChannels1: 16           # Number of channels for the first set of layers
nrChannels2: 24          # Number of channels for the second set of layers
nrChannels3: 36           # Number of channels for the third set of layers
nrChannels4: 48          # Number of channels for the fourth set of layers
drop_prob: 0.02       # Dropout probability

## So far best configuration got 82.5% on the validation se unett