defaults:
  - model: AdaptedDeepLabV3Plus
  - writer: tensorboard 
  - metrics: metrics
  - datasets: image_road 
  - dataloader: main
  - transforms: noisy
  - trainer: main
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}
loss_function:
  _target_: src.loss.BinaryCrossEntropyLoss
experiment:
  name: AdaptedDeepLabV3Plus 