defaults:
  - model: unet_small
  - writer: tensorboard 
  - metrics: metrics
  - datasets: image
  - dataloader: main
  - transforms: flip_erase
  - trainer: main
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}
loss_function:
  _target_: src.loss.BinaryCrossEntropyLoss

trainer:
  n_epochs:  20
  epoch_len: 100

experiment: 
  name: exp_arch_unet_large